title: Giovanni Lupo
author: Giovanni Lupo
description: Projects, the Light Phone III, and other things I build.
url: "https://gzl.dev"
timezone: America/New_York
markdown: kramdown
permalink: /blog/:title/
plugins:
  - jekyll-feed
